const LESSONS = {
  airport: {
    name: 'Аэропорт ✈️',
    description: 'Регистрация, безопасность, перелёты',
    timestamp: 1,
    items: [
      { ru: "Аэропорт", en: "Airport" },
      { ru: "Регистрация на рейс", en: "Check-in" },
      { ru: "Посадочный талон", en: "Boarding pass" },
      { ru: "Паспортный контроль", en: "Passport control" },
      { ru: "Контроль безопасности", en: "Security check" },
      { ru: "Ручная кладь", en: "Hand luggage" },
      { ru: "Сдаваемый багаж", en: "Checked baggage" },
      { ru: "Выход на посадку", en: "Gate" },
      { ru: "Посадка", en: "Boarding" },
      { ru: "Задержка рейса", en: "Flight delay" },
      { ru: "Отменённый рейс", en: "Cancelled flight" },
      { ru: "Пересадка", en: "Layover" },
      { ru: "Прилет", en: "Arrival" },
      { ru: "Вылет", en: "Departure" },
      { ru: "Таможенная декларация", en: "Customs declaration" },
      { ru: "Потерять багаж", en: "Lose luggage" },
      { ru: "Компенсация", en: "Compensation" },
      { ru: "Проходить досмотр", en: "Go through security" }
    ]
  },

  restaurant: {
    name: 'Ресторан 🍽️',
    description: 'Заказ еды, сервис, жалобы',
    timestamp: 2,
    items: [
      { ru: "Ресторан", en: "Restaurant" },
      { ru: "Забронировать столик", en: "Book a table" },
      { ru: "Меню", en: "Menu" },
      { ru: "Рекомендация от шефа", en: "Chef’s special" },
      { ru: "Сделать заказ", en: "Place an order" },
      { ru: "Основное блюдо", en: "Main course" },
      { ru: "Закуска", en: "Starter" },
      { ru: "Десерт", en: "Dessert" },
      { ru: "Напитки", en: "Beverages" },
      { ru: "Счёт", en: "Bill" },
      { ru: "Чаевые", en: "Tip" },
      { ru: "Обслуживание", en: "Service" },
      { ru: "Перепутать заказ", en: "Mix up an order" },
      { ru: "Пожаловаться", en: "Make a complaint" },
      { ru: "Острое блюдо", en: "Spicy dish" },
      { ru: "Без лактозы", en: "Lactose-free" },
      { ru: "Сытный", en: "Filling" },
      { ru: "Стоит своих денег", en: "Worth the money" }
    ]
  },

  shop: {
    name: 'Магазин 🛍️',
    description: 'Покупки, возвраты, выбор',
    timestamp: 3,
    items: [
      { ru: "Магазин", en: "Shop" },
      { ru: "Цена", en: "Price" },
      { ru: "Скидка", en: "Discount" },
      { ru: "Распродажа", en: "Sale" },
      { ru: "Касса", en: "Checkout" },
      { ru: "Очередь", en: "Queue" },
      { ru: "Возврат товара", en: "Return an item" },
      { ru: "Обмен", en: "Exchange" },
      { ru: "Размер", en: "Size" },
      { ru: "Примерить", en: "Try on" },
      { ru: "Качество", en: "Quality" },
      { ru: "Дешёвый", en: "Cheap" },
      { ru: "Дорогой", en: "Expensive" },
      { ru: "Стоит купить", en: "Worth buying" },
      { ru: "Импульсивная покупка", en: "Impulse purchase" },
      { ru: "Чек", en: "Receipt" },
      { ru: "Способ оплаты", en: "Payment method" }
    ]
  },

  library: {
    name: 'Библиотека 📚',
    description: 'Чтение, учёба, исследования',
    timestamp: 4,
    items: [
      { ru: "Библиотека", en: "Library" },
      { ru: "Записаться", en: "Register" },
      { ru: "Книга", en: "Book" },
      { ru: "Автор", en: "Author" },
      { ru: "Жанр", en: "Genre" },
      { ru: "Взять книгу", en: "Borrow a book" },
      { ru: "Вернуть книгу", en: "Return a book" },
      { ru: "Продлить срок", en: "Extend the loan" },
      { ru: "Каталог", en: "Catalogue" },
      { ru: "Учебное пособие", en: "Study guide" },
      { ru: "Источники", en: "Sources" },
      { ru: "Исследование", en: "Research" },
      { ru: "Тишина", en: "Silence" },
      { ru: "Доступ онлайн", en: "Online access" },
      { ru: "Редкое издание", en: "Rare edition" }
    ]
  },

  transport: {
    name: 'Транспорт 🚍',
    description: 'Город, маршруты, проблемы',
    timestamp: 5,
    items: [
      { ru: "Общественный транспорт", en: "Public transport" },
      { ru: "Автобус", en: "Bus" },
      { ru: "Поезд", en: "Train" },
      { ru: "Метро", en: "Subway" },
      { ru: "Остановка", en: "Stop" },
      { ru: "Станция", en: "Station" },
      { ru: "Билет", en: "Ticket" },
      { ru: "Проездной", en: "Travel pass" },
      { ru: "Опоздать", en: "Miss" },
      { ru: "Пересадка", en: "Transfer" },
      { ru: "Пробка", en: "Traffic jam" },
      { ru: "Задержка", en: "Delay" },
      { ru: "Маршрут", en: "Route" },
      { ru: "Час пик", en: "Rush hour" },
      { ru: "Ненадёжный", en: "Unreliable" },
      { ru: "Удобный", en: "Convenient" }
    ]
  },

  dailyLife: {
    name: 'Повседневная жизнь ☕',
    description: 'Рутина, привычки, планы',
    timestamp: 6,
    items: [
      { ru: "Просыпаться", en: "Wake up" },
      { ru: "Засыпать", en: "Fall asleep" },
      { ru: "Распорядок дня", en: "Daily routine" },
      { ru: "Успевать", en: "Manage to" },
      { ru: "Откладывать дела", en: "Put things off" },
      { ru: "Соблюдать баланс", en: "Maintain balance" },
      { ru: "Чувствовать усталость", en: "Feel exhausted" },
      { ru: "Перегруженный график", en: "Tight schedule" },
      { ru: "Выделить время", en: "Make time for" },
      { ru: "Привычка", en: "Habit" },
      { ru: "Изменить образ жизни", en: "Change lifestyle" },
      { ru: "Справляться", en: "Cope with" },
      { ru: "Планировать заранее", en: "Plan ahead" },
      { ru: "Отменить планы", en: "Cancel plans" },
      { ru: "Выгорание", en: "Burnout" }
    ]
  },
  crimeAndJustice: {
    name: 'Преступление ⚖️',
    description: 'Закон, правонарушения, наказания',
    timestamp: 7,
    items: [
      { ru: "Неожиданно", en: "Out of the blue" },
      { ru: "Отправить оплату", en: "Send a fee" },
      { ru: "Обман", en: "Scam" },
      { ru: "Мошенник", en: "Fraudster" },
      { ru: "Доверчивые люди", en: "Gullible people" },
      { ru: "Виновный", en: "Culprits" },
      { ru: "Вламываться в", en: "Break into" },
      { ru: "Поймать с поличным", en: "Catch red-handed" },
      { ru: "Давать показания", en: "Give evidence" },
      { ru: "Выхватить телефон", en: "Grab a phone" },
      { ru: "Угрожать", en: "Threaten" },
      { ru: "Сознаться в преступлении", en: "Confess to the crime" },
      { ru: "Тюремный срок", en: "Prison sentence" },
      { ru: "Получить синяк", en: "Bruise" },
      { ru: "Вытереть, стереть", en: "Wipe off" },
      { ru: "Отвлекать", en: "Distract" },
      { ru: "Отправиться под суд", en: "Take to court" },
      { ru: "Нарушение ПДД", en: "Driving offence" },
      { ru: "Пожизненное заключение", en: "Life sentence" },
      { ru: "Признать виновным", en: "Find guilty" },
      { ru: "Свидетель", en: "Witness" },
      { ru: "Оплатить штраф", en: "Pay a fine" },
      { ru: "Преследовать", en: "Chase after" },
      { ru: "Скрыться с деньгами", en: "Make off with the money" },
      { ru: "Повестись на", en: "Fall for" },
      { ru: "Так называемый прохожий", en: "So-called passer by" },
      { ru: "Развести, обмануть", en: "Take for a ride" },
      { ru: "Грабить банк", en: "Rob" },
      { ru: "Грабить дом", en: "Burgle" },
      { ru: "Грабить на улице", en: "Mug" },
      { ru: "Красть из магазина", en: "Shoplift" },
      { ru: "Грабить", en: "Steal" },
      { ru: "Портить что-то", en: "Vandalise" },
      { ru: "Украсть человека", en: "Kidnap" },
      { ru: "Жертва", en: "Victim" }
    ]
  },
  crimeAndJustice2: {
    name: 'Правопорядок 👩🏼‍⚖️',
    description: 'Права, юрисдикция, ответсвенность',
    timestamp: 8,
    items: [
      { ru: "Нарушать права", en: "Violate rights" },
      { ru: "Не увеличивать", en: "Keep down" },
      { ru: "Быть против закона", en: "Be against the law" },
      { ru: "Поручить", en: "Give responsibility of" },
      { ru: "Держаться подальше от", en: "Keep away from" },
      { ru: "Быть обвиненным в", en: "Be charged with" },
      { ru: "Отвергать основные права человека", en: "Deny basic human rights" },
      { ru: "Продолжать", en: "Keep on" },
      { ru: "Требования чего-либо", en: "Requirements of" },
      { ru: "Брать ответственность", en: "Accept responsibility" },
      { ru: "Скрывать", en: "Keep back" },
      { ru: "Обмануть в чем-то", en: "Trick into" },
      { ru: "Относиться плохо", en: "Treat badly" },
      { ru: "Отстаивать права", en: "Stand up for one's rights" },
      { ru: "Защищать права", en: "Defend the rights" },
      { ru: "Беречь от", en: "Keep from" },
      { ru: "Терпеть отношение", en: "Tolerate attitude" },
      { ru: "Не отставать", en: "Keep up with" },
      { ru: "Быть ответственным за", en: "Be responsible for" }
    ]
  },
  SurvivalAndTrauma: {
    name: 'Выживание 🦴',
    description: 'Части тела, Травмы, Выживание',
    timestamp: 9,
    items: [
      { ru: "Вопреки всему", en: "Against all odds" },
      { ru: "История выживания", en: "Tale of survival" },
      { ru: "Мучительное решение", en: "Agonising decision" },
      { ru: "Смелый", en: "Bold"},
      { ru: "Непреодолимый вызов", en: "Irresistible challenge" },
      { ru: "Достичь вершины", en: "Reach the summit" },
      { ru: "Быть искалеченным", en: "Be crippled" },
      { ru: "В полной темноте", en: "In the pitch black" },
      { ru: "Скала", en: "Cliff" },
      { ru: "Быть обмороженным", en: "Be frostbitten" },
      { ru: "Чудесным образом", en: "Miraculously" },
      { ru: "Покорять", en: "Conquer" },
      { ru: "Проявление силы воли", en: "Display of willpower" },
      { ru: "Споткнуться", en: "Trip over" },
      { ru: "Синяк", en: "Bruise" },
      { ru: "Голень", en: "Shin" },
      { ru: "Перелом", en: "Fracture" },
      { ru: "Ключица", en: "Collarbone" },
      { ru: "Бедро", en: "Hip" },
      { ru: "Растяжение связок", en: "Sprain" },
      { ru: "Лодыжка", en: "Ankle" },
      { ru: "Запястье", en: "Wrist" },
      { ru: "Затекший", en: "Stiff" },
      { ru: "Царапина", en: "Scratch" },
      { ru: "Опухший", en: "Swollen" },
      { ru: "Предположительно", en: "Supposedly" },
      { ru: "Подниматься", en: "Ascend" },
      { ru: "Спуск", en: "Descent" },
      { ru: "Сделать попытку", en: "Make an attempt" }
    ]
  },
  health: {
    name: 'Здоровье 🩺',
    description: 'Симптомы, болезни, состояние',
    timestamp: 10,
    items: [
      { ru: "Иметь сердечный приступ", en: "Have a heart attack" },
      { ru: "Иметь расстройство желудка", en: "Be vomiting" },
      { ru: "Массово заболевать / умирать", en: "Drop like flies" },
      { ru: "Простудиться", en: "Catch a cold" },
      { ru: "Иметь боль в мышцах", en: "Have aching muscles" },
      { ru: "Насморк", en: "Running nose" },
      { ru: "Плохо выглядеть", en: "Look off colour" },
      { ru: "Чувствовать головокружение", en: "Feel dizzy" },
      { ru: "Иметь сыпь", en: "Have a rash" },
      { ru: "Чувствовать недомогание", en: "Be under the weather" },
      { ru: "Продолжать", en: "Go on" },
      { ru: "Хрипеть, задыхаться", en: "Wheeze" },
      { ru: "Поправиться после болезни", en: "Be back on your feet" },
      { ru: "Высморкаться", en: "Blow the nose" },
      { ru: "Чувствовать изнеможение", en: "Feel run down" },
      { ru: "Чихать", en: "Sneeze" },
      { ru: "Жаловаться на", en: "Complain of" },
      { ru: "Начать, продолжить", en: "Go ahead with" },
      { ru: "Мучительная боль", en: "Excruciating pain" },
      { ru: "Иметь аллергию на", en: "Be allergic to" },
      { ru: "Оправиться от", en: "Recover from" },
      { ru: "Быть вовлечённым в", en: "Be involved in" },
      { ru: "Лечиться от", en: "Treat for" },
      { ru: "Быть покрытым чем-либо", en: "Be covered in" },
      { ru: "Острая боль", en: "Severe pain" },
      { ru: "Футбольная травма", en: "Football injury" },
      { ru: "Болезненный", en: "Painful" },
      { ru: "Чудом спастись", en: "Narrow escape" },
      { ru: "Внутреннее кровотечение", en: "Internal bleeding" },
      { ru: "Быть без сознания", en: "Be unconscious" },
      { ru: "Охрипнуть", en: "Sound hoarse" },
      { ru: "Обсуждать в деталях", en: "Go into" },
      { ru: "Упасть в обморок / потерять сознание", en: "Faint / lose consciousness" },
      { ru: "Иметь боль в горле", en: "Have a sore throat" },
      { ru: "Затекла шея", en: "Have a stiff neck" }
    ]
  },
  city_and_life: {
    name: 'Город и Жизнь 🏙️',
    description: 'Условия проживания, городская среда и социальные аспекты',
    timestamp: 11,
    items: [
      { ru: "Делать что-то с неохотой", en: "Be reluctant to" },
      { ru: "Приёмная семья", en: "Foster home" },
      { ru: "Диван", en: "Couch" },
      { ru: "Дрожать от холода", en: "Shiver with cold" },
      { ru: "Временное жильё", en: "Temporary accommodation" },
      { ru: "Редкие ночи", en: "Odd nights" },
      { ru: "Ночлежки", en: "Squats" },
      { ru: "Заброшенный дом", en: "Abandoned house" },
      { ru: "Тесная комната", en: "Cramped room" },
      { ru: "Наркоман", en: "Drug addict" },
      { ru: "Грязный", en: "Filthy" },
      { ru: "Душить", en: "Choke" },
      { ru: "Сводить концы с концами", en: "Make ends meet" },
      { ru: "Бросать (монету)", en: "Toss" },
      { ru: "Шикарный, роскошный", en: "Posh" },
      { ru: "Личность", en: "Identity" },
      { ru: "Достоинство", en: "Dignity" },
      { ru: "Порочный круг", en: "Vicious circle" },
      { ru: "Самооценка", en: "Self-esteem" },
      { ru: "Быстрорастущий город", en: "Boom town" },
      { ru: "Город-трущоба", en: "Shanty town" },
      { ru: "Дом в плохом состоянии", en: "Run-down house" },
      { ru: "Дом с мебелью", en: "Fully-furnished house" },
      { ru: "Заброшенный склад", en: "Disused warehouse" },
      { ru: "Жилой район", en: "Residential area" },
      { ru: "Пешеходная улица (район)", en: "Pedestrianised street (area)" }
    ]
  }
};
